# Generated by Django 6.0.1 on 2026-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('CRICKET', 'Cricket'), ('FOOTBALL', 'Football'), ('BADMINTON', 'Badminton'), ('TENNIS', 'Tennis'), ('OTHER', 'Other')], max_length=20)),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_time', models.TimeField(default='06:00')),
                ('closing_time', models.TimeField(default='23:00')),
                ('slot_duration_mins', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
